#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.24.2
if [ -z "$DPKG_ROOT" ] && [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'vyatta-gnssd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_vci_enable/UNDECLARED
deb-vci-helper remove vyatta-service-gnss >/dev/null
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p vyatta-service-gnss 
else
	dpkg -L vyatta-service-gnss | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section
